# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: wbraeckm <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/05/16 08:28:47 by wbraeckm          #+#    #+#              #
#    Updated: 2018/05/16 08:33:25 by wbraeckm         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
SRCS = srcs/ft_display_file.c

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror $(SRCS) -I includes/ -o $(NAME)

clean:

fclean:
	rm -f $(NAME)

re: fclean all
